apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: 4111
    targetPort: 3111
    protocol: TCP
  selector:
    app: techtrends
  type: ClusterIP
