apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
spec:
  project: default
  source:
    helm:
    valuesFiles:
      - values-staging.yaml
    releaseName: techtrends-staging
    chart: techtrends
    version: 1.0.0
    repoURL: https://github.com/quoclong1914/nd064_course_1
    path: project/helm
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  