apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
spec:
  project: default
  source:
    repoURL: https://github.com/quoclong1914/nd064_course_1
    path: project/helm
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  helm:
    valuesFiles:
      - values-prod.yaml
    releaseName: techtrends-prod
    chart: techtrends
    version: 1.0.0